name: Combine Wordlists

on:
  push:
    branches:
      - main
      - dev
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  fetch_wordlists:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create wordlists directory
        run: mkdir -p ~/Wordlists

      - name: Fetch wordlists
        id: fetch
        run: |
          python -c "
          import os
          import subprocess
          import json

          def fetch_wordlists_from_file():
              urls = []
              with open('urls.txt', 'r') as f:
                  urls = [line.strip() for line in f.readlines()]
              return urls

          urls = fetch_wordlists_from_file()
          wordlist_urls = []
          for url in urls:
              if url.startswith('http'):
                  wordlist_urls.append(url)
              else:
                  api_url = f'https://api.github.com/repos/{url}/contents/'
                  result = subprocess.run(['curl', '-s', api_url], capture_output=True, text=True)
                  if result.returncode == 0:
                      contents = json.loads(result.stdout)
                      for item in contents:
                          if item['name'].endswith('.txt'):
                              wordlist_urls.append(item["download_url"])

          for wordlist_url in wordlist_urls:
              result = subprocess.run(['curl', '-s', wordlist_url], capture_output=True, text=True)
              if result.returncode == 0:
                  with open(os.path.expanduser('~/Wordlists/wordlists.txt'), 'a') as f:
                      f.write(result.stdout)
          "

  process_wordlists:
    runs-on: ubuntu-latest
    needs: fetch_wordlists
    steps:
      - name: Merge and remove duplicates
        run: |
          cat ~/Wordlists/wordlists.txt | sort -u > ~/Wordlists/merged_wordlists.txt

  test_script:
    runs-on: ubuntu-latest
    needs: process_wordlists
    steps:
      - name: Test Python
        run: python --version

  deploy:
    runs-on: ubuntu-latest
    needs: test_script
    steps:
      - name: Upload merged wordlists
        uses: actions/upload-artifact@v4
        with:
          name: merged-wordlists
          path: ~/Wordlists/merged_wordlists.txt
